<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Syncomm_Serial_Monitor</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <Platform>x64</Platform>
    <UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
  </PropertyGroup>
	<PropertyGroup>
		<EnableMsixTooling>true</EnableMsixTooling>
		<EnableXamlCompiler>false</EnableXamlCompiler>
	</PropertyGroup>
	<ItemGroup>
	  <Content Remove="Assets\serialplot.png" />
	  <Content Remove="Assets\SplashScreen.scale-200.png" />
	</ItemGroup>
  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Collections" Version="8.2.250402" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.250402" />
    <PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.250402" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
    <PackageReference Include="FluentIcons.WinUI" Version="1.1.303" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4654" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
    <PackageReference Include="ScottPlot.WinUI" Version="5.0.55" />
    <PackageReference Include="System.Runtime.WindowsRuntime.UI.Xaml" Version="4.7.0" />
    <PackageReference Include="System.IO.Ports" Version="9.0.8" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\serialplot.png" />
    <Resource Include="Assets\SplashScreen.scale-200.png" />
  </ItemGroup>


</Project>